// profile
export const REGISTER_NAME = 'REGISTER_NAME'
export const REGISTER_COMPANY = 'REGISTER_COMPANY'
export const REGISTER_JOB = 'REGISTER_JOB'

// skill
// common
export const UPDATE_PROGRAMMING = 'UPDATE_PROGRAMMING'
export const UPDATE_SOFTWARE_DESIGN = 'UPDATE_SOFTWARE_DESIGN'
export const UPDATE_MAN_HOUR_ESTIMATE = 'UPDATE_MAN_HOUR_ESTIMATE'
export const UPDATE_MEETING = 'UPDATE_MEETING'
export const UPDATE_CROSS_DEPARTMENTAL = 'UPDATE_CROSS_DEPARTMENTAL'

// unique
export const UPDATE_UNIQUE_SKILL_NAME = 'UPDATE_UNIQUE_SKILL_NAME' 
export const UPDATE_UNIQUE_SKILL_DESCRIPTION = 'UPDATE_UNIQUE_SKILL_DESCRIPTION' 

// numerical
export const ADD_NUMERICAL_SKILL = 'ADD_NUMERICAL_SKILL'
export const REMOVE_NUMERICAL_SKILL = 'REMOVE_NUMERICAL_SKILL'
export const IMPORT_NUMERICAL_SKILLS = 'IMPORT_NUMERICAL_SKILLS'

// special
export const ADD_SPECIAL_SKILL = 'ADD_SPECIAL_SKILL'
export const REMOVE_SPECIAL_SKILL = 'REMOVE_SPECIAL_SKILL'
export const IMPORT_SPECIAL_SKILLS = 'IMPORT_SPECIAL_SKILLS'